spring:
  datasource:
    platform: hsqldb
    url: jdbc:h2:mem:issuetracker
    username: sa
    platform: 
    url: jdbc:postgresql://localhost:5432/mydb
    username: 
    password: 
  jpa:
   show-sql: true
   hibernate.ddl-auto: update
---
spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
         binder: rabbit
         destination: payments
         content-type: application/json
         
---
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
